"use client";

import React, { useState, useEffect, useMemo, useCallback } from "react";
import { createPortal } from "react-dom";
import { Modal, Button, useToast, Badge } from "@/components/ui";
import type { User } from "@/lib/types/database";
import type { TodayShiftMonitorRow } from "@/lib/data/operations/today-shift-monitor";
import { formatDate, getISTDateString } from "@reachinternational/utils";
import {
  handleBrowserPrint,
  PDFReportHeader,
  PDFKPIStrip,
  PDFSignatureBlock,
  PDFTableWrapper,
  getPrintStylesheet,
} from "@/components/pdf";
import { exportTodayShiftLogsToExcel } from "@/lib/utils/today-shift-export";
import {
  Printer,
  FileSpreadsheet,
} from "lucide-react";

const PRINT_DOC_ID = "printable-today-shifts-document";
const PREVIEW_ID = "printable-today-shifts-document-preview";

export interface TodayShiftExportModalProps {
  open: boolean;
  onClose: () => void;
  rows: TodayShiftMonitorRow[];
  user?: User;
}

const formatTime12H = (t?: string | null): string => {
  if (!t) return "—";
  try {
    const [h, m] = t.split(":").map(Number);
    if (isNaN(h)) return t;
    const ampm = h >= 12 ? "PM" : "AM";
    const h12 = h % 12 || 12;
    return `${h12}:${String(m || 0).padStart(2, "0")} ${ampm}`;
  } catch {
    return t;
  }
};

function TodayShiftsReportContent({
  rows,
  dateStr,
  userName,
}: {
  rows: TodayShiftMonitorRow[];
  dateStr: string;
  userName: string;
}) {
  const total = rows.length;
  const entered = rows.filter((r) => r.status === "entered").length;
  const pending = rows.filter((r) => r.status === "pending").length;
  const unassigned = rows.filter((r) => r.status === "unassigned" || !r.operator_id).length;
  const totalRunningHours = rows.reduce(
    (acc, r) => acc + (typeof r.running_hours === "number" ? r.running_hours : 0),
    0
  );

  const kpis = [
    { label: "Total Shifts", value: String(total) },
    { label: "Entered Logs", value: String(entered), valueColor: "text-emerald-700" },
    { label: "Pending Logs", value: String(pending), valueColor: "text-amber-700" },
    { label: "Unassigned", value: String(unassigned), valueColor: "text-red-700" },
    { label: "Total Running Hours", value: `${totalRunningHours.toFixed(1)}h`, valueColor: "text-sky-700" },
  ];

  const signatures = [
    { heading: "Site Supervisor", name: "Operations Supervisor", role: "(Site Supervisor)", detail: formatDate(dateStr) },
    { heading: "Operations Manager", name: userName, role: "(Operations Manager)", detail: formatDate(dateStr) },
    { heading: "Authorized Signatory", name: "Reach International", role: "(Authorized Signatory)", detail: formatDate(dateStr) },
  ];

  return (
    <div className="pdf-document w-full max-w-[1080px] bg-white text-neutral-900 p-6 sm:p-8 space-y-6">
      {/* Centralized PDF Header */}
      <PDFReportHeader
        title="TODAY'S SHIFT LOGS MONITOR"
        subtitle="Daily Operational Shift Coverage, Operator Roster & Hour Meter Readings"
        metadataItems={[
          { label: "Date", value: `${formatDate(dateStr)} (${dateStr})` },
          { label: "Generated By", value: userName },
          { label: "Print Date", value: new Date().toLocaleDateString("en-IN", { dateStyle: "medium" }) },
        ]}
      />

      {/* KPI Summary Strip */}
      <PDFKPIStrip items={kpis} />

      {/* High Density Table */}
      <PDFTableWrapper>
        <table className="w-full text-[11px] text-left border-collapse">
          <thead>
            <tr className="bg-neutral-100 text-neutral-700 font-semibold border-b border-neutral-300">
              <th className="w-[4%] text-center py-2 px-2">#</th>
              <th className="w-[16%] py-2 px-2">Operator</th>
              <th className="w-[18%] py-2 px-2">Machine</th>
              <th className="w-[18%] py-2 px-2">Client / Site</th>
              <th className="w-[16%] py-2 px-2">Shift & Timing</th>
              <th className="w-[10%] text-center py-2 px-2">Status</th>
              <th className="w-[18%] text-right py-2 px-2">HMR Reading</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r, idx) => {
              const isEntered = r.status === "entered";
              const isUnassigned = r.status === "unassigned" || !r.operator_id;
              const timings =
                r.shift_start && r.shift_end
                  ? `${formatTime12H(r.shift_start)} – ${formatTime12H(r.shift_end)}`
                  : "—";

              return (
                <tr
                  key={r.operator_id ? `${r.operator_id}-${r.machine_id}-${idx}` : `unassigned-${r.machine_id}-${idx}`}
                  className={idx % 2 === 0 ? "bg-white" : "bg-neutral-50/60"}
                  style={{ borderBottom: "1px solid #ebebeb" }}
                >
                  <td className="text-center font-mono text-[11px] text-neutral-500 py-2 px-2">{idx + 1}</td>
                  <td className="py-2 px-2">
                    <div className="font-semibold text-xs text-neutral-900 truncate">
                      {isUnassigned ? "Unassigned Machine" : r.operator_name || "—"}
                    </div>
                    {r.operator_phone && !isUnassigned && (
                      <div className="text-[10px] text-neutral-500 font-mono">{r.operator_phone}</div>
                    )}
                  </td>
                  <td className="py-2 px-2 font-mono">
                    <div className="font-bold text-xs text-neutral-900">
                      {r.machine_serial_number || r.machine_code}
                    </div>
                    <div className="text-[10px] text-neutral-500">
                      {r.machine_model && `${r.machine_model} · `}
                      {r.machine_code}
                    </div>
                  </td>
                  <td className="py-2 px-2">
                    <div className="text-xs text-neutral-900 font-medium truncate">{r.client_name || "—"}</div>
                    {(r.client_code || r.client_id) && (
                      <div className="text-[10px] text-neutral-500 font-mono">{r.client_code || r.client_id}</div>
                    )}
                  </td>
                  <td className="py-2 px-2">
                    <div className="text-xs font-semibold text-neutral-800">
                      {r.shift_code ? `Shift ${r.shift_code}` : "—"}
                      {r.shift_name && <span className="font-normal text-neutral-500"> ({r.shift_name})</span>}
                    </div>
                    <div className="text-[10px] text-neutral-500">{timings}</div>
                  </td>
                  <td className="py-2 px-2 text-center">
                    <span
                      style={{
                        display: "inline-block",
                        padding: "2px 6px",
                        borderRadius: "4px",
                        fontSize: "10px",
                        fontWeight: 700,
                        textTransform: "uppercase",
                        backgroundColor: isEntered ? "#ecfdf5" : isUnassigned ? "#fef2f2" : "#fffbeb",
                        color: isEntered ? "#059669" : isUnassigned ? "#dc2626" : "#d97706",
                        border: `1px solid ${isEntered ? "#a7f3d0" : isUnassigned ? "#fecaca" : "#fde68a"}`,
                      }}
                    >
                      {isEntered ? "Entered" : isUnassigned ? "Unassigned" : "Pending"}
                    </span>
                  </td>
                  <td className="py-2 px-2 text-right font-mono text-xs">
                    {isEntered ? (
                      <div>
                        <div className="font-semibold text-neutral-900">
                          {r.start_meter ?? 0} → {r.end_meter ?? 0}
                        </div>
                        {r.running_hours != null && (
                          <div className="text-[10px] font-bold text-sky-600">
                            {r.running_hours} hrs run
                          </div>
                        )}
                      </div>
                    ) : (
                      <span className="text-neutral-400">—</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </PDFTableWrapper>

      {/* Signature Section */}
      <PDFSignatureBlock columns={signatures} />
    </div>
  );
}

export function TodayShiftExportModal({
  open,
  onClose,
  rows,
  user,
}: TodayShiftExportModalProps) {
  const { toast } = useToast();
  const [mounted, setMounted] = useState(false);
  const dateStr = useMemo(() => getISTDateString(), []);
  const userName = user?.full_name || "Manager";

  useEffect(() => {
    setMounted(true);
  }, []);

  const total = rows.length;
  const entered = rows.filter((r) => r.status === "entered").length;
  const pending = rows.filter((r) => r.status === "pending").length;

  const pdfFileName = `Today_Shift_Monitor_${dateStr}`;

  const handleExportExcel = useCallback(() => {
    if (rows.length === 0) {
      toast("info", "No Data", "No shifts available to export for today.");
      return;
    }
    try {
      exportTodayShiftLogsToExcel(rows, dateStr);
      toast("success", "Excel Exported", `Today's shift logs saved to ${pdfFileName}.xlsx`);
    } catch (err: any) {
      toast("error", "Export Failed", err?.message || "Failed to generate Excel file.");
    }
  }, [rows, dateStr, pdfFileName, toast]);

  const handlePrintPdf = useCallback(() => {
    if (rows.length === 0) {
      toast("info", "No Data", "No shifts available to export for today.");
      return;
    }
    handleBrowserPrint(pdfFileName);
  }, [rows.length, pdfFileName, toast]);

  return (
    <>
      {/* Centralized Print Stylesheet */}
      <style>{getPrintStylesheet(PRINT_DOC_ID, PREVIEW_ID, {
        includePreviewStyles: true,
        includeKpiStrip: true,
      })}</style>

      {/* Print Portal */}
      {mounted && open && createPortal(
        <div id={PRINT_DOC_ID}>
          <TodayShiftsReportContent rows={rows} dateStr={dateStr} userName={userName} />
        </div>,
        document.body
      )}

      {/* Interactive Modal */}
      <Modal
        open={open}
        onClose={onClose}
        title={
          <div className="flex items-center gap-2 pr-6">
            <span className="text-base sm:text-lg font-extrabold text-[var(--color-ink)]">
              Export Today's Shift Logs
            </span>
            <Badge variant="info" className="text-[10px] font-mono px-2 py-0.5">
              {formatDate(dateStr)}
            </Badge>
          </div>
        }
        size="xl"
        footer={
          <div className="flex flex-col sm:flex-row items-center justify-between gap-3 w-full pt-1 no-print">
            <div className="text-xs text-[var(--color-mute)] font-medium text-center sm:text-left">
              <span>Ready to export <strong>{total}</strong> shifts ({entered} entered, {pending} pending).</span>
            </div>
            <div className="flex items-center gap-2 flex-wrap justify-end w-full sm:w-auto">
              <Button
                variant="outline"
                onClick={handleExportExcel}
                disabled={rows.length === 0}
                icon={<FileSpreadsheet size={14} className="text-emerald-600 dark:text-emerald-400 shrink-0" />}
                className="h-9 px-3 text-xs font-bold border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-500/20 cursor-pointer shadow-2xs"
                title="Export as Excel (.xlsx)"
              >
                Export Excel (.xlsx)
              </Button>

              <Button
                variant="outline"
                onClick={handlePrintPdf}
                disabled={rows.length === 0}
                icon={<Printer size={14} className="text-sky-600 dark:text-sky-400 shrink-0" />}
                className="h-9 px-3 text-xs font-bold border-sky-500/30 bg-sky-500/10 text-sky-700 dark:text-sky-300 hover:bg-sky-500/20 cursor-pointer shadow-2xs"
                title="Print or Save as PDF"
              >
                Print / Save PDF
              </Button>

            </div>
          </div>
        }
      >
        <div className="max-w-full">
          {/* Document Preview Box */}
          <div className="rounded-xl border border-[var(--color-hairline)] bg-[var(--color-canvas)] p-2 sm:p-4 max-h-[50vh] overflow-y-auto custom-scrollbar">
            <div id={PREVIEW_ID} className="w-full flex justify-center">
              <TodayShiftsReportContent rows={rows} dateStr={dateStr} userName={userName} />
            </div>
          </div>
        </div>
      </Modal>
    </>
  );
}
