import * as XLSX from "xlsx";
import type { CRMClient } from "@/lib/types/database";
import type { ClientExportRecord } from "@/lib/data/clients/client-export";
import { formatDate } from "@reachinternational/utils";
import { formatExportDateTimeSlug, PDF_BRANDING } from "@/lib/pdf/pdf-config";
import { handleBrowserPrint } from "@/lib/pdf/pdf-utils";

export interface NormalizedClientExportItem {
  clientId: string;
  companyName: string;
  contactPerson: string;
  phone: string;
  gstin: string;
  pan: string;
  siteAddress: string;
  city: string;
  district: string;
  state: string;
  pincode: string;
  isBillingDiff: boolean;
  billingAddress: string;
  status: string;
  createdAt: string;
}

export function buildClientsExportFileName(
  prefix: string = "Client-Directory",
  extension: "xlsx" | "csv" | "pdf"
): string {
  const { slugDateTime } = formatExportDateTimeSlug();
  const cleanPrefix = prefix.replace(/[^a-zA-Z0-9-_]+/g, "-");
  return `${cleanPrefix}-${slugDateTime}.${extension}`;
}

export function normalizeClientForExport(c: any): NormalizedClientExportItem {
  const clientId = c.client_id || c.code || "—";
  const companyName = c.company_name || c.client_name || "—";
  const contactPerson = c.contact_person || "—";
  const phone = c.phone || "—";
  const gstin = c.gstin || "—";
  const pan = c.pan_number || "—";

  const siteAddress =
    c.site_address ||
    c.address ||
    [c.street, c.city, c.district, c.state, c.pincode].filter(Boolean).join(", ") ||
    "—";

  const city = c.city || "—";
  const district = c.district || "—";
  const state = c.state || "—";
  const pincode = c.pincode || "—";

  const isBillingDiff = Boolean(c.is_billing_different ?? c.is_billing_address_different);
  const billingAddress = isBillingDiff
    ? c.billing_address ||
      [c.billing_city, c.billing_district, c.billing_state, c.billing_pincode]
        .filter(Boolean)
        .join(", ") ||
      "Separate Billing Address"
    : "Same as Site Address";

  let status = "ACTIVE";
  if (c.deleted_at || c.status === "SOFT DELETED") {
    status = "SOFT DELETED";
  } else if (c.status?.toLowerCase() === "inactive") {
    status = "INACTIVE";
  } else if (typeof c.status === "string") {
    status = c.status.toUpperCase();
  }

  let createdAt = "—";
  if (c.created_at) {
    try {
      createdAt = formatDate(c.created_at);
    } catch {
      createdAt = String(c.created_at);
    }
  }

  return {
    clientId,
    companyName,
    contactPerson,
    phone,
    gstin,
    pan,
    siteAddress,
    city,
    district,
    state,
    pincode,
    isBillingDiff,
    billingAddress,
    status,
    createdAt,
  };
}

export const CLIENT_EXPORT_COLUMNS = [
  "S.No",
  "Client ID",
  "Company Name",
  "Contact Person",
  "Mobile Phone",
  "GSTIN",
  "PAN Number",
  "Site Address / Location",
  "City",
  "District",
  "State",
  "Pincode",
  "Separate Billing",
  "Billing Address",
  "Account Status",
  "Registration Date",
];

export function exportClientsToExcel(
  clients: (CRMClient | ClientExportRecord)[],
  filenamePrefix: string = "Client-Directory"
) {
  if (!clients || clients.length === 0) return;

  const { displayDateTime } = formatExportDateTimeSlug();
  const normalized = clients.map(normalizeClientForExport);

  const titleRow = ["REACH INTERNATIONAL — CLIENT DIRECTORY REPORT"];
  const metaRow = [
    `Total Clients Exported: ${clients.length}`,
    `Export Date: ${displayDateTime}`,
    `Generated By: ReachInternational Client Operations`,
  ];
  const blankRow = [""];

  let activeCount = 0;
  let inactiveCount = 0;

  const dataRows = normalized.map((item, index) => {
    if (item.status === "ACTIVE") activeCount++;
    else inactiveCount++;

    return [
      index + 1,
      item.clientId,
      item.companyName,
      item.contactPerson,
      item.phone,
      item.gstin,
      item.pan,
      item.siteAddress,
      item.city,
      item.district,
      item.state,
      item.pincode,
      item.isBillingDiff ? "Yes" : "No",
      item.billingAddress,
      item.status,
      item.createdAt,
    ];
  });

  const summaryRow = [
    `TOTAL: ${clients.length} Clients | Active: ${activeCount} | Inactive / Soft-Deleted: ${inactiveCount}`,
  ];

  const worksheetData = [
    titleRow,
    metaRow,
    blankRow,
    CLIENT_EXPORT_COLUMNS,
    ...dataRows,
    blankRow,
    summaryRow,
  ];

  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  worksheet["!cols"] = [
    { wch: 8 },  // S.No
    { wch: 16 }, // Client ID
    { wch: 30 }, // Company Name
    { wch: 22 }, // Contact Person
    { wch: 18 }, // Phone
    { wch: 18 }, // GSTIN
    { wch: 15 }, // PAN
    { wch: 36 }, // Site Address
    { wch: 16 }, // City
    { wch: 16 }, // District
    { wch: 16 }, // State
    { wch: 12 }, // Pincode
    { wch: 16 }, // Separate Billing
    { wch: 36 }, // Billing Address
    { wch: 16 }, // Status
    { wch: 18 }, // Registration Date
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Client Directory");

  const fileName = buildClientsExportFileName(filenamePrefix, "xlsx");
  XLSX.writeFile(workbook, fileName);
}

export function exportClientsToCSV(
  clients: (CRMClient | ClientExportRecord)[],
  filenamePrefix: string = "Client-Directory"
) {
  if (!clients || clients.length === 0) return;

  const normalized = clients.map(normalizeClientForExport);

  const escapeCSV = (value: string | number | null | undefined): string => {
    if (value === null || value === undefined) return '""';
    const str = String(value).replace(/"/g, '""');
    return `"${str}"`;
  };

  const rows = normalized.map((item, index) => [
    index + 1,
    item.clientId,
    item.companyName,
    item.contactPerson,
    item.phone,
    item.gstin,
    item.pan,
    item.siteAddress,
    item.city,
    item.district,
    item.state,
    item.pincode,
    item.isBillingDiff ? "Yes" : "No",
    item.billingAddress,
    item.status,
    item.createdAt,
  ]);

  const csvContent = [
    CLIENT_EXPORT_COLUMNS.map(escapeCSV).join(","),
    ...rows.map((row) => row.map(escapeCSV).join(",")),
  ].join("\r\n");

  const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const fileName = buildClientsExportFileName(filenamePrefix, "csv");

  link.setAttribute("href", url);
  link.setAttribute("download", fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

const CLIENTS_PRINT_DOC_ID = "printable-clients-directory-document";

export function generateClientsReportHtml(
  clients: (CRMClient | ClientExportRecord)[],
  scopeLabel: string = "Full Directory"
): string {
  const { displayDateTime } = formatExportDateTimeSlug();
  const normalized = clients.map(normalizeClientForExport);

  let activeCount = 0;
  let inactiveCount = 0;
  const uniqueCities = new Set<string>();

  normalized.forEach((c) => {
    if (c.status === "ACTIVE") activeCount++;
    else inactiveCount++;
    if (c.city && c.city !== "—") uniqueCities.add(c.city);
  });

  const rowsHtml = normalized
    .map((c, index) => {
      const isEven = index % 2 === 0;
      const rowBg = isEven ? "#ffffff" : "#fbfbfb";
      const statusColor =
        c.status === "ACTIVE"
          ? "#059669"
          : c.status === "INACTIVE"
          ? "#d97706"
          : "#dc2626";

      return `
        <tr style="background-color: ${rowBg}; page-break-inside: avoid;">
          <td style="padding: 5px 4px; border: 1px solid #d4d4d4; text-align: center; font-size: 8.5px; font-weight: bold; font-family: monospace;">${index + 1}</td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 8.5px; font-weight: 700; font-family: monospace; color: #0284c7; white-space: nowrap;">${c.clientId}</td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 9px; font-weight: 700; color: #111827;">${c.companyName}</td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 8px; color: #4b5563; font-family: monospace;">
            ${c.gstin !== "—" ? `<div>GST: ${c.gstin}</div>` : ""}
            ${c.pan !== "—" ? `<div>PAN: ${c.pan}</div>` : ""}
            ${c.gstin === "—" && c.pan === "—" ? "—" : ""}
          </td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 8.5px; font-weight: 500; color: #1f2937;">${c.contactPerson}</td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 8.5px; font-family: monospace; color: #111827; white-space: nowrap;">${c.phone}</td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 8px; color: #4b5563; line-height: 1.25;">${c.siteAddress}</td>
          <td style="padding: 5px 4px; border: 1px solid #d4d4d4; text-align: center; font-size: 8px; font-weight: 700; color: ${statusColor};">${c.status}</td>
          <td style="padding: 5px 6px; border: 1px solid #d4d4d4; font-size: 8.5px; font-family: monospace; color: #4b5563; text-align: center; white-space: nowrap;">${c.createdAt}</td>
        </tr>
      `;
    })
    .join("");

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #171717; background-color: #ffffff; padding: 12px 16px; max-width: 297mm; margin: 0 auto; box-sizing: border-box;">
      <!-- Header Banner -->
      <div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #171717; padding-bottom: 10px; margin-bottom: 12px;">
        <div>
          <div style="font-size: 15px; font-weight: 900; letter-spacing: 0.5px; color: #111827; text-transform: uppercase;">
            ${PDF_BRANDING.companyName}
          </div>
          <div style="font-size: 12px; font-weight: 700; color: #374151; margin-top: 2px;">
            CLIENT DIRECTORY &amp; MASTER PROJECT REGISTRY
          </div>
          <div style="font-size: 9.5px; color: #6b7280; margin-top: 2px;">
            Official Client Accounts, Operational Sites, Tax Records &amp; Contact Details
          </div>
        </div>
        <div style="text-align: right; font-size: 9px; color: #4b5563; line-height: 1.4;">
          <div><strong>Report Scope:</strong> ${scopeLabel}</div>
          <div><strong>Total Exported:</strong> ${clients.length} Clients</div>
          <div><strong>Export Date:</strong> ${displayDateTime}</div>
          <div><strong>Generated By:</strong> Client Operations Desk</div>
        </div>
      </div>

      <!-- KPI Summary Cards Strip -->
      <div style="display: flex; gap: 8px; margin-bottom: 12px;">
        <div style="flex: 1; background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 6px 10px;">
          <div style="font-size: 8px; font-weight: 700; text-transform: uppercase; color: #6b7280; letter-spacing: 0.5px;">Total Accounts</div>
          <div style="font-size: 15px; font-weight: 800; color: #111827; margin-top: 2px;">${clients.length}</div>
        </div>
        <div style="flex: 1; background-color: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 6px; padding: 6px 10px;">
          <div style="font-size: 8px; font-weight: 700; text-transform: uppercase; color: #047857; letter-spacing: 0.5px;">Active Accounts</div>
          <div style="font-size: 15px; font-weight: 800; color: #065f46; margin-top: 2px;">${activeCount}</div>
        </div>
        <div style="flex: 1; background-color: #fffbeb; border: 1px solid #fde68a; border-radius: 6px; padding: 6px 10px;">
          <div style="font-size: 8px; font-weight: 700; text-transform: uppercase; color: #b45309; letter-spacing: 0.5px;">Inactive / Churned</div>
          <div style="font-size: 15px; font-weight: 800; color: #92400e; margin-top: 2px;">${inactiveCount}</div>
        </div>
        <div style="flex: 1; background-color: #f5f3ff; border: 1px solid #ddd6fe; border-radius: 6px; padding: 6px 10px;">
          <div style="font-size: 8px; font-weight: 700; text-transform: uppercase; color: #6d28d9; letter-spacing: 0.5px;">Active Cities</div>
          <div style="font-size: 15px; font-weight: 800; color: #5b21b6; margin-top: 2px;">${uniqueCities.size}</div>
        </div>
      </div>

      <!-- 9-Column High-Density Report Table -->
      <table style="width: 100%; border-collapse: collapse; border: 1px solid #171717; margin-bottom: 16px;">
        <thead>
          <tr style="background-color: #171717; color: #ffffff;">
            <th style="padding: 6px 4px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; width: 3%;">S.N</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: left; width: 10%;">Client ID</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: left; width: 22%;">Company Name</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: left; width: 12%;">Tax &amp; Compliance</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: left; width: 13%;">Contact Person</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: left; width: 11%;">Phone</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: left; width: 17%;">Site Location</th>
            <th style="padding: 6px 4px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: center; width: 6%;">Status</th>
            <th style="padding: 6px 6px; border: 1px solid #374151; font-size: 8px; font-weight: 800; text-transform: uppercase; text-align: center; width: 6%;">Registered</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>

      <!-- Signatures Footer -->
      <div style="display: flex; justify-content: space-between; margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; page-break-inside: avoid;">
        <div style="width: 28%; text-align: center;">
          <div style="height: 36px;"></div>
          <div style="border-top: 1px dashed #9ca3af; padding-top: 4px; font-size: 9px; font-weight: 700; color: #1f2937;">Prepared By</div>
          <div style="font-size: 8px; color: #6b7280;">(Client Relations &amp; Operations)</div>
        </div>
        <div style="width: 28%; text-align: center;">
          <div style="height: 36px;"></div>
          <div style="border-top: 1px dashed #9ca3af; padding-top: 4px; font-size: 9px; font-weight: 700; color: #1f2937;">Billing &amp; Tax Verification</div>
          <div style="font-size: 8px; color: #6b7280;">(Commercial Division)</div>
        </div>
        <div style="width: 28%; text-align: center;">
          <div style="height: 36px;"></div>
          <div style="border-top: 1px dashed #9ca3af; padding-top: 4px; font-size: 9px; font-weight: 700; color: #1f2937;">Verified &amp; Approved By</div>
          <div style="font-size: 8px; font-weight: 800; color: #111827;">REACH INTERNATIONAL</div>
          <div style="font-size: 8px; color: #6b7280;">(Executive Authority)</div>
        </div>
      </div>
    </div>
  `;
}

export function exportClientsToPDF(
  clients: (CRMClient | ClientExportRecord)[],
  filenamePrefix: string = "Client-Directory",
  scopeLabel: string = "Full Directory"
) {
  if (!clients || clients.length === 0) return;

  const fileName = buildClientsExportFileName(filenamePrefix, "pdf");

  const styleId = "clients-pdf-print-styles";
  if (!document.getElementById(styleId)) {
    const styleEl = document.createElement("style");
    styleEl.id = styleId;
    styleEl.innerHTML = `
      @media screen {
        #${CLIENTS_PRINT_DOC_ID} {
          display: none !important;
        }
      }
      @media print {
        @page {
          size: landscape A4;
          margin: 6mm 8mm 6mm 8mm;
        }
        html, body {
          background: #ffffff !important;
          color: #000000 !important;
          height: auto !important;
          min-height: 0 !important;
          overflow: visible !important;
          position: static !important;
          margin: 0 !important;
          padding: 0 !important;
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
        }
        body > *:not(#${CLIENTS_PRINT_DOC_ID}) {
          display: none !important;
        }
        #${CLIENTS_PRINT_DOC_ID} {
          display: block !important;
          position: static !important;
          width: 100% !important;
          margin: 0 !important;
          padding: 0 !important;
          visibility: visible !important;
        }
        #${CLIENTS_PRINT_DOC_ID} * {
          visibility: visible !important;
        }
      }
    `;
    document.head.appendChild(styleEl);
  }

  let container = document.getElementById(CLIENTS_PRINT_DOC_ID);
  if (!container) {
    container = document.createElement("div");
    container.id = CLIENTS_PRINT_DOC_ID;
    document.body.appendChild(container);
  }

  container.innerHTML = generateClientsReportHtml(clients, scopeLabel);

  handleBrowserPrint(fileName);
}
