import * as XLSX from "xlsx";
import type { Machine } from "@/lib/types/database";
import { formatDate } from "@reachinternational/utils";

function formatRentalStatus(status?: string): string {
  switch (status) {
    case "rented":
      return "On Rent";
    case "available":
      return "Available";
    case "maintenance":
      return "Under Maintenance";
    case "retired":
      return "Retired";
    default:
      return status ? status.charAt(0).toUpperCase() + status.slice(1).replace(/_/g, " ") : "Available";
  }
}

function formatHealthStatus(health?: string): string {
  switch (health) {
    case "active":
      return "Active (Healthy)";
    case "under_maintenance":
      return "Under Maintenance";
    case "breakdown":
      return "Breakdown";
    default:
      return health ? health.charAt(0).toUpperCase() + health.slice(1).replace(/_/g, " ") : "Active";
  }
}

// Generate formatted date & time slug for filename & reports
export function formatMachinesExportDateTimeSlug(dateObj: Date = new Date()): {
  displayDateTime: string;
  slugDateTime: string;
} {
  const day = String(dateObj.getDate()).padStart(2, "0");
  const month = String(dateObj.getMonth() + 1).padStart(2, "0");
  const year = dateObj.getFullYear();
  const hours = String(dateObj.getHours()).padStart(2, "0");
  const minutes = String(dateObj.getMinutes()).padStart(2, "0");

  const displayDateTime = `${day}-${month}-${year} ${hours}:${minutes}`;
  const slugDateTime = `${day}-${month}-${year}-${hours}-${minutes}`;
  return { displayDateTime, slugDateTime };
}

export function buildMachinesExportFileName(
  prefix: string = "Machine-Directory",
  extension: "xlsx" | "csv" | "pdf"
): string {
  const { slugDateTime } = formatMachinesExportDateTimeSlug();
  const cleanPrefix = prefix.replace(/[^a-zA-Z0-9-_]+/g, "-");
  return `${cleanPrefix}-${slugDateTime}.${extension}`;
}

export function exportMachinesToExcel(
  machines: Machine[],
  filenamePrefix: string = "Machine-Directory"
) {
  if (!machines || machines.length === 0) return;

  const { displayDateTime } = formatMachinesExportDateTimeSlug();

  // Top Title & Metadata
  const titleRow = ["REACH INTERNATIONAL — MACHINE FLEET INVENTORY REPORT"];
  const metaRow = [
    `Total Machines Exported: ${machines.length}`,
    `Export Date: ${displayDateTime}`,
    `Generated By: ReachInternational Fleet Portal`,
  ];
  const blankRow = [""];

  // Table Headers
  const tableHeaders = [
    "S.No",
    "Machine ID",
    "Model",
    "Serial Number",
    "Manufacturer",
    "Year of Mfg (YUM)",
    "Hour Meter (HMR hrs)",
    "Rental Status",
    "Health Status",
    "Assigned Client",
    "Deployment Location",
    "Current Supervisor",
    "Current Operator",
    "Registration Date",
  ];

  let availableCount = 0;
  let rentedCount = 0;
  let breakdownCount = 0;
  let maintenanceCount = 0;
  let activeHealthCount = 0;
  let totalHmr = 0;

  // Data Rows
  const dataRows = machines.map((m, index) => {
    if (m.status === "rented") rentedCount++;
    else availableCount++;

    if (m.health_status === "breakdown") breakdownCount++;
    else if (m.health_status === "under_maintenance") maintenanceCount++;
    else activeHealthCount++;

    const hmr = Number(m.hour_meter) || 0;
    totalHmr += hmr;

    const supervisorName = m.current_supervisor?.full_name || "Unassigned";
    const operatorName = m.current_operator?.full_name || "Unassigned";
    const clientName = m.client?.company_name
      ? `${m.client.company_name}${m.client.code ? ` (${m.client.code})` : ""}`
      : (m.customer_name || "Unassigned");
    const location = m.client?.city
      ? `${m.client.city}${m.client.state ? `, ${m.client.state}` : ""}`
      : ((m as any).customer_address || (m as any).city || (m as any).location || "—");
    const createdAtStr = m.created_at ? formatDate(m.created_at) : "—";

    return [
      index + 1,
      m.machine_id || "—",
      m.model || "—",
      m.serial_number || "—",
      m.manufacturer || "—",
      m.year_of_mfg || "—",
      hmr,
      formatRentalStatus(m.status),
      formatHealthStatus(m.health_status),
      clientName,
      location,
      supervisorName,
      operatorName,
      createdAtStr,
    ];
  });

  // Summary Row
  const summaryRow = [
    "SUMMARY TOTALS",
    `Total: ${machines.length} Machines`,
    "",
    "",
    "",
    `Fleet HMR: ${Math.round(totalHmr * 10) / 10} hrs`,
    "",
    `Available: ${availableCount} | Rented: ${rentedCount}`,
    `Active: ${activeHealthCount} | Maint: ${maintenanceCount} | Breakdown: ${breakdownCount}`,
    "",
    "",
    "",
    "",
    "",
  ];

  const worksheetData = [
    titleRow,
    metaRow,
    blankRow,
    tableHeaders,
    ...dataRows,
    blankRow,
    summaryRow,
  ];

  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Column Widths
  worksheet["!cols"] = [
    { wch: 8 },  // S.No
    { wch: 18 }, // Machine ID
    { wch: 22 }, // Model
    { wch: 20 }, // Serial Number
    { wch: 18 }, // Manufacturer
    { wch: 18 }, // Year of Mfg
    { wch: 20 }, // Hour Meter
    { wch: 18 }, // Rental Status
    { wch: 22 }, // Health Status
    { wch: 26 }, // Assigned Client
    { wch: 28 }, // Deployment Location
    { wch: 22 }, // Current Supervisor
    { wch: 22 }, // Current Operator
    { wch: 18 }, // Registration Date
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Machine Directory");

  const fileName = buildMachinesExportFileName(filenamePrefix, "xlsx");
  XLSX.writeFile(workbook, fileName);
}

export function exportMachinesToCSV(
  machines: Machine[],
  filenamePrefix: string = "Machine-Directory"
) {
  if (!machines || machines.length === 0) return;

  const headers = [
    "S.No",
    "Machine ID",
    "Model",
    "Serial Number",
    "Manufacturer",
    "Year of Mfg",
    "Hour Meter Reading (hrs)",
    "Rental Status",
    "Health Status",
    "Assigned Client",
    "Deployment Location",
    "Current Supervisor",
    "Current Operator",
    "Registration Date",
  ];

  const escapeCSV = (value: string | number | null | undefined): string => {
    if (value === null || value === undefined) return '""';
    const str = String(value).replace(/"/g, '""');
    return `"${str}"`;
  };

  const rows = machines.map((m, index) => {
    const supervisorName = m.current_supervisor?.full_name || "Unassigned";
    const operatorName = m.current_operator?.full_name || "Unassigned";
    const clientName = m.client?.company_name
      ? `${m.client.company_name}${m.client.code ? ` (${m.client.code})` : ""}`
      : (m.customer_name || "Unassigned");
    const location = m.client?.city
      ? `${m.client.city}${m.client.state ? `, ${m.client.state}` : ""}`
      : ((m as any).customer_address || (m as any).city || (m as any).location || "");
    const createdAtStr = m.created_at ? formatDate(m.created_at) : "";

    return [
      index + 1,
      m.machine_id || "",
      m.model || "",
      m.serial_number || "",
      m.manufacturer || "",
      m.year_of_mfg || "",
      m.hour_meter || 0,
      formatRentalStatus(m.status),
      formatHealthStatus(m.health_status),
      clientName,
      location,
      supervisorName,
      operatorName,
      createdAtStr,
    ];
  });

  const csvContent = [
    headers.map(escapeCSV).join(","),
    ...rows.map((row) => row.map(escapeCSV).join(",")),
  ].join("\r\n");

  // UTF-8 BOM for Excel compatibility
  const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const fileName = buildMachinesExportFileName(filenamePrefix, "csv");

  link.setAttribute("href", url);
  link.setAttribute("download", fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
