import * as XLSX from "xlsx";
import type { User } from "@/lib/types/database";
import { formatDate, maskAadhaar, formatLicenseNumber } from "@reachinternational/utils";

function formatRoleName(role: string): string {
  switch (role) {
    case "super_admin":
      return "Super Admin";
    case "admin":
      return "Admin";
    case "manager":
    case "branch_manager":
      return "Manager";
    case "service_manager":
      return "Service Manager";
    case "service_engineer":
    case "engineer":
      return "Service Engineer";
    case "supervisor":
      return "Supervisor";
    case "store_manager":
      return "Store Manager";
    case "operator":
      return "Operator";
    case "mechanic":
      return "Mechanic";
    case "hr_manager":
      return "HR Manager";
    default:
      return role ? role.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) : "User";
  }
}

function formatStatus(status: string): string {
  switch (status) {
    case "active":
      return "Active";
    case "inactive":
      return "Inactive";
    case "pending":
      return "Pending Approval";
    default:
      return status ? status.charAt(0).toUpperCase() + status.slice(1) : "—";
  }
}

// Generate formatted date & time slug for filename
export function formatUsersExportDateTimeSlug(dateObj: Date = new Date()): { displayDateTime: string; slugDateTime: string } {
  const day = String(dateObj.getDate()).padStart(2, "0");
  const month = String(dateObj.getMonth() + 1).padStart(2, "0");
  const year = dateObj.getFullYear();
  const hours = String(dateObj.getHours()).padStart(2, "0");
  const minutes = String(dateObj.getMinutes()).padStart(2, "0");

  const displayDateTime = `${day}-${month}-${year} ${hours}:${minutes}`;
  const slugDateTime = `${day}-${month}-${year}-${hours}-${minutes}`;
  return { displayDateTime, slugDateTime };
}

export function buildUsersExportFileName(
  prefix: string = "Users-Directory",
  extension: "xlsx" | "csv"
): string {
  const { slugDateTime } = formatUsersExportDateTimeSlug();
  const cleanPrefix = prefix.replace(/[^a-zA-Z0-9-_]+/g, "-");
  return `${cleanPrefix}-${slugDateTime}.${extension}`;
}

export function exportUsersToExcel(users: User[], filenamePrefix: string = "Users-Directory") {
  if (!users || users.length === 0) return;

  const { displayDateTime } = formatUsersExportDateTimeSlug();

  // Top Title & Metadata
  const titleRow = ["REACH INTERNATIONAL — USER & EMPLOYEE DIRECTORY REPORT"];
  const metaRow = [
    `Total Users Exported: ${users.length}`,
    `Export Date: ${displayDateTime}`,
    `Generated By: System Administrator`,
  ];
  const blankRow = [""];

  // Table Headers
  const tableHeaders = [
    "S.No",
    "Full Name",
    "Email Address",
    "Mobile Number",
    "Role",
    "Status",
    "City",
    "District",
    "State",
    "Aadhaar Number",
    "Driving Licence",
    "Joined Date",
  ];

  let activeCount = 0;
  let pendingCount = 0;
  let inactiveCount = 0;

  // Data Rows
  const dataRows = users.map((u, index) => {
    if (u.status === "active") activeCount++;
    else if (u.status === "pending") pendingCount++;
    else if (u.status === "inactive") inactiveCount++;

    return [
      index + 1,
      u.full_name || "—",
      u.email || "—",
      u.phone || "—",
      formatRoleName(u.role),
      formatStatus(u.status),
      u.city || u.location || "—",
      u.district || "—",
      u.state || "—",
      u.aadhaar_number ? maskAadhaar(u.aadhaar_number) : "—",
      u.license_number ? formatLicenseNumber(u.license_number) : "—",
      u.created_at ? formatDate(u.created_at) : "—",
    ];
  });

  // Summary Row
  const summaryRow = [
    "SUMMARY TOTALS",
    `Total: ${users.length} Users`,
    `Active: ${activeCount}`,
    `Pending: ${pendingCount}`,
    `Inactive: ${inactiveCount}`,
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ];

  const worksheetData = [
    titleRow,
    metaRow,
    blankRow,
    tableHeaders,
    ...dataRows,
    blankRow,
    summaryRow,
  ];

  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Column Widths
  worksheet["!cols"] = [
    { wch: 8 },  // S.No
    { wch: 26 }, // Full Name
    { wch: 30 }, // Email Address
    { wch: 18 }, // Mobile Number
    { wch: 20 }, // Role
    { wch: 18 }, // Status
    { wch: 18 }, // City
    { wch: 18 }, // District
    { wch: 18 }, // State
    { wch: 18 }, // Aadhaar
    { wch: 20 }, // Licence
    { wch: 16 }, // Joined Date
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Users Directory");

  const fileName = buildUsersExportFileName(filenamePrefix, "xlsx");
  XLSX.writeFile(workbook, fileName);
}

export function exportUsersToCSV(users: User[], filenamePrefix: string = "Users-Directory") {
  if (!users || users.length === 0) return;

  const headers = [
    "S.No",
    "Full Name",
    "Email Address",
    "Mobile Number",
    "Role",
    "Status",
    "City",
    "District",
    "State",
    "Aadhaar Number",
    "Driving Licence",
    "Joined Date",
  ];

  const escapeCSV = (value: string | number | null | undefined): string => {
    if (value === null || value === undefined) return '""';
    const str = String(value).replace(/"/g, '""');
    return `"${str}"`;
  };

  const rows = users.map((u, index) => [
    index + 1,
    u.full_name || "",
    u.email || "",
    u.phone || "",
    formatRoleName(u.role),
    formatStatus(u.status),
    u.city || u.location || "",
    u.district || "",
    u.state || "",
    u.aadhaar_number ? maskAadhaar(u.aadhaar_number) : "",
    u.license_number ? formatLicenseNumber(u.license_number) : "",
    u.created_at ? formatDate(u.created_at) : "",
  ]);

  const csvContent = [
    headers.map(escapeCSV).join(","),
    ...rows.map((row) => row.map(escapeCSV).join(",")),
  ].join("\r\n");

  // UTF-8 BOM for Excel compatibility
  const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const fileName = buildUsersExportFileName(filenamePrefix, "csv");

  link.setAttribute("href", url);
  link.setAttribute("download", fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
